---
blank_issues_enabled: false
contact_links:
  - name: JaxUtils Community Support
    url: https://github.com/JaxGaussianProcesses/JaxUtils/discussions
    about: Please ask and answer questions here.
